import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Post.module.css'
import Header from '../../components/header'
import Link from 'next/link'
import { useEffect } from 'react'
import { FaAngleRight, FaClock, FaRegClock, FaStar } from 'react-icons/fa'


export default function MovieItem({ info }) {

    function BackgroundImg() {
        const main = document.querySelector('.mainPost')
        main.style.backgroundImage = `url(https://image.tmdb.org/t/p/original${info.backdrop_path})`
    }
    useEffect(() => {
        BackgroundImg()
    }, [])

    return (
        <div className={styles.container}>
            <Head>
                <title>SamFlix</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* SERVER SIDE RENDER PAGE  -------------- */}
            {/* SERVER SIDE RENDER PAGE  -------------- */}
            {/* SERVER SIDE RENDER PAGE  -------------- */}
            {/* SERVER SIDE RENDER PAGE  -------------- */}
            {/* <div>

            </div> */}




            <main className={'mainPost'}>
                <div className={'blackmodala'}>
                </div>
                <Header />
                {/* <h1 className={styles.title}>
                    Filmes:
                </h1>
                <Link href={'/busca'}>Ir para busca</Link>

                <h1>{info.title}</h1>
                <img src={`https://image.tmdb.org/t/p/original${info.poster_path}`} width='500px' />
                <p className={styles.paragraph}>{info.overview}</p>
                <span>Nota: {info.vote_average}</span> */}

                <div className={styles.mainPostContainer}>
                    <div className={styles.posterheadflex}>
                        <div className={styles.posterheadflex1}>
                            <img className={styles.imgposter} src={`https://image.tmdb.org/t/p/original${info.poster_path}`} />
                        </div>
                        <div className={styles.posterheadflex2}>
                            <h3>Assistir {info.title} Online
                            </h3>
                            <h1>
                                {info.title}

                            </h1>
                            <div className={styles.filmdata}>
                                <span>2022</span>
                                <span><FaRegClock />  2h, 5min</span>
                                <span>7.2/10</span>
                                <span> <FaStar /> <FaStar /> <FaStar /> <FaStar className={styles.lose} /> <FaStar className={styles.lose} /> </span>
                                <span>Trailer <FaAngleRight/> </span>
                            </div>
                            <div className={styles.authordivs}></div>
                        </div>

                    </div>
                </div>

            </main>




        </div>
    )
}

export async function getServerSideProps(context) {
    const id = context.params.id
    const resposta = await fetch(`http://localhost:3000/api/movie/${id}`)
    const json = await resposta.json()

    // console.log("JSON", json)

    return {
        props: {
            info: json.info
        }
    }
}