import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import Header from '../../components/header'
import Link from 'next/link'


export default function MovieItem({ info }) {

    return (
        <div className={styles.container}>
            <Head>
                <title>SamFlix</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className={styles.header}>
                <Link href={'/'}><h4 className={styles.h4}>Voltar ao home</h4></Link>
            </header>

            {/* SERVER SIDE RENDER PAGE  -------------- */}
            {/* SERVER SIDE RENDER PAGE  -------------- */}
            {/* SERVER SIDE RENDER PAGE  -------------- */}
            {/* SERVER SIDE RENDER PAGE  -------------- */}



            <main className={styles.main}>
                <h1 className={styles.title}>
                    Filmes:
                </h1>
                <Link href={'/busca'}>Ir para busca</Link>

                <h1>{info.title}</h1>
                <img src={`https://image.tmdb.org/t/p/original${info.backdrop_path}`} width='500px' />
                <p className={styles.paragraph}>{info.overview}</p>
                <span>Nota: {info.vote_average}</span>

            </main>


        </div>
    )
}

export async function getServerSideProps(context) {
    const id = context.params.id
    const resposta = await fetch(`http://localhost:3000/api/movie/${id}`)
    const json = await resposta.json()

    // console.log("JSON", json)

    return {
        props: {
            info: json.info
        }
    }
}