import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/header'
import Link from 'next/link'
import { useEffect } from 'react'
import Footer from '../components/footersobre'
export default function Sobre({ autor }) {


    useEffect(() => {
        localStorage.setItem('pagina', 3)
    }, [])


    //STATIC PAGE ------------------------
    //STATIC PAGE ------------------------
    //STATIC PAGE ------------------------
    //STATIC PAGE ------------------------



    return (
        <>
            <div className={styles.containerfooter}>
                <Head>
                    <title>SamFlix - Sobre</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                    <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
                    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
                </Head>
                <div className={styles.container100}>
                    <Header />

                </div>
                <main className={styles.main}>
                    {/* <h1 className={styles.title}>
                        O sistema é feito usando Server side render e client side render, e também static render. esta página é estatica.
                    </h1>
                    <h2>Autor: {autor}</h2> */}
                    <div className={styles.whitebackgroundiv}>
                        <div className={styles.whitebackgroundivcontainer}>
                            <h1>SAMFLIX</h1>
                            <p>Aplicação construida para fins didaticos. Ferramenta principal: NextJs. Lorem ipsum dolor sit amet,
                                consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
                                quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
                                reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>


                            <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium,
                                totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo.
                                Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit,
                                sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.
                                Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur,
                                adipisci velit,
                                sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
                                Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam,
                                nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse
                                quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
                        </div>
                    </div>
                </main>
                <Footer estilo='0px' />
            </div>
        </>

    )
}

export async function getStaticProps() {
    const resposta = await fetch('http://localhost:3000/api/trending')
    const json = await resposta.json()
    return {
        props: {
            autor: 'Samyr'
        }
    }
}